server:
  port: 8085
  servlet:
    context-path: /elm_api
spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/elm?useSSL=false'
    username: 'root'
    password: 'Ncy18225889352'
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 30
      minimum-idle: 5
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: false

knife4j:
  enable: true
  setting:
    language: zh_cn
  basic:
    enable: true
    username: admin
    password: 123456